// <auto-generated />
using BHYTDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BHYTDashboard.Migrations
{
    [DbContext(typeof(BenhVienUbContext))]
    partial class BenhVienUbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BHYTDashboard.Models.Entities.ChiTietDvkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DonGia")
                        .HasColumnType("int");

                    b.Property<string>("MaBacSi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaDichVu")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaLk")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MaLK");

                    b.Property<string>("MaNhomChiPhi")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaVatTu")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("NgayKetQua")
                        .HasColumnType("int");

                    b.Property<int?>("NgayYlenh")
                        .HasColumnType("int")
                        .HasColumnName("NgayYLenh");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenDichVu")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TenVatTu")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("ThanhTien")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ChiTietD__3214EC07508B6BB4");

                    b.HasIndex("MaLk");

                    b.HasIndex("MaNhomChiPhi");

                    b.ToTable("ChiTietDVKT", (string)null);
                });

            modelBuilder.Entity("BHYTDashboard.Models.Entities.ChiTietThuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DonGia")
                        .HasColumnType("int");

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaLk")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MaLK");

                    b.Property<string>("MaNhomChiPhi")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaThuoc")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenThuoc")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("ThanhTien")
                        .HasColumnType("int");

                    b.Property<int?>("TyLeThanhToan")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ChiTietT__3214EC076F5A254A");

                    b.HasIndex("MaLk");

                    b.HasIndex("MaNhomChiPhi");

                    b.ToTable("ChiTietThuoc", (string)null);
                });

            modelBuilder.Entity("BHYTDashboard.Models.Entities.DanhMucDoiTuong", b =>
                {
                    b.Property<string>("MaDoiTuong")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TenDoiTuong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaDoiTuong")
                        .HasName("PK__DanhMucD__291408A164B5DC2E");

                    b.ToTable("DanhMucDoiTuong", (string)null);
                });

            modelBuilder.Entity("BHYTDashboard.Models.Entities.DanhMucIcd10", b =>
                {
                    b.Property<string>("MaIcd")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaICD");

                    b.Property<string>("TenBenh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("MaIcd")
                        .HasName("PK__DanhMucI__3B5EE75567E3A4FA");

                    b.ToTable("DanhMucICD10", (string)null);
                });

            modelBuilder.Entity("BHYTDashboard.Models.Entities.DanhMucNhomChiPhi", b =>
                {
                    b.Property<string>("MaNhomChiPhi")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TenNhomChiPhi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaNhomChiPhi")
                        .HasName("PK__DanhMucN__40482F3C9128A357");

                    b.ToTable("DanhMucNhomChiPhi", (string)null);
                });

            modelBuilder.Entity("BHYTDashboard.Models.Entities.HoSoBenhNhan", b =>
                {
                    b.Property<string>("MaLk")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MaLK");

                    b.Property<string>("ChanDoanRa")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ChanDoanVao")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1024)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaBenhChinh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaBn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MaBN");

                    b.Property<string>("MaCskcb")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaCSKCB");

                    b.Property<string>("MaDoiTuong")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaTheBhyt")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MaTheBHYT");

                    b.Property<int>("NgayRa")
                        .HasColumnType("int");

                    b.Property<int>("NgaySinh")
                        .HasColumnType("int");

                    b.Property<int>("NgayVao")
                        .HasColumnType("int");

                    b.Property<int?>("TongBenhNhanTra")
                        .HasColumnType("int");

                    b.Property<int?>("TongBhchiTra")
                        .HasColumnType("int")
                        .HasColumnName("TongBHChiTra");

                    b.Property<int?>("TongChiPhi")
                        .HasColumnType("int");

                    b.HasKey("MaLk")
                        .HasName("PK__HoSoBenh__2725C77A7CB7A511");

                    b.HasIndex("MaBenhChinh");

                    b.HasIndex("MaDoiTuong");

                    b.ToTable("HoSoBenhNhan", (string)null);
                });

            modelBuilder.Entity("BHYTDashboard.Models.Entities.ChiTietDvkt", b =>
                {
                    b.HasOne("BHYTDashboard.Models.Entities.HoSoBenhNhan", "MaLkNavigation")
                        .WithMany("ChiTietDvkts")
                        .HasForeignKey("MaLk")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDVK__MaLK__3C69FB99");

                    b.HasOne("BHYTDashboard.Models.Entities.DanhMucNhomChiPhi", "MaNhomChiPhiNavigation")
                        .WithMany("ChiTietDvkts")
                        .HasForeignKey("MaNhomChiPhi")
                        .HasConstraintName("FK__ChiTietDV__MaNho__45F365D3");

                    b.Navigation("MaLkNavigation");

                    b.Navigation("MaNhomChiPhiNavigation");
                });

            modelBuilder.Entity("BHYTDashboard.Models.Entities.ChiTietThuoc", b =>
                {
                    b.HasOne("BHYTDashboard.Models.Entities.HoSoBenhNhan", "MaLkNavigation")
                        .WithMany("ChiTietThuocs")
                        .HasForeignKey("MaLk")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietThu__MaLK__398D8EEE");

                    b.HasOne("BHYTDashboard.Models.Entities.DanhMucNhomChiPhi", "MaNhomChiPhiNavigation")
                        .WithMany("ChiTietThuocs")
                        .HasForeignKey("MaNhomChiPhi")
                        .HasConstraintName("FK__ChiTietTh__MaNho__44FF419A");

                    b.Navigation("MaLkNavigation");

                    b.Navigation("MaNhomChiPhiNavigation");
                });

            modelBuilder.Entity("BHYTDashboard.Models.Entities.HoSoBenhNhan", b =>
                {
                    b.HasOne("BHYTDashboard.Models.Entities.DanhMucIcd10", "MaBenhChinhNavigation")
                        .WithMany("HoSoBenhNhans")
                        .HasForeignKey("MaBenhChinh")
                        .HasConstraintName("FK__HoSoBenhN__MaBen__440B1D61");

                    b.HasOne("BHYTDashboard.Models.Entities.DanhMucDoiTuong", "MaDoiTuongNavigation")
                        .WithMany("HoSoBenhNhans")
                        .HasForeignKey("MaDoiTuong")
                        .HasConstraintName("FK__HoSoBenhN__MaDoi__4316F928");

                    b.Navigation("MaBenhChinhNavigation");

                    b.Navigation("MaDoiTuongNavigation");
                });

            modelBuilder.Entity("BHYTDashboard.Models.Entities.DanhMucDoiTuong", b =>
                {
                    b.Navigation("HoSoBenhNhans");
                });

            modelBuilder.Entity("BHYTDashboard.Models.Entities.DanhMucIcd10", b =>
                {
                    b.Navigation("HoSoBenhNhans");
                });

            modelBuilder.Entity("BHYTDashboard.Models.Entities.DanhMucNhomChiPhi", b =>
                {
                    b.Navigation("ChiTietDvkts");

                    b.Navigation("ChiTietThuocs");
                });

            modelBuilder.Entity("BHYTDashboard.Models.Entities.HoSoBenhNhan", b =>
                {
                    b.Navigation("ChiTietDvkts");

                    b.Navigation("ChiTietThuocs");
                });
#pragma warning restore 612, 618
        }
    }
}
